Repository awell-health/design-system, pull requests merged in 2024-10, with the labels that each got.

#137 feat: new components for decision modeling
  package.json
  src/components/ui/decision-editor/code.tsx
  src/components/ui/decision-editor/expression.tsx
  src/components/ui/decision-editor/graph.tsx
  src/components/ui/decision-editor/index.ts
  src/components/ui/decision-editor/table.tsx
  src/stories/DecisionEditor.stories.tsx
  yarn.lock
Labels: enhancement, Tests, Review effort [1-5]: 3

#139 Add disabled option to select
  package.json
  src/components/ui/select/select.tsx
  src/stories/Select.stories.tsx
Labels: enhancement, Review effort [1-5]: 2

#138 chore: remove decision editor components and gorules package
  package.json
  src/components/index.ts
  src/components/ui/decision-editor/code.tsx
  src/components/ui/decision-editor/expression.tsx
  src/components/ui/decision-editor/graph.tsx
  src/components/ui/decision-editor/index.ts
  src/components/ui/decision-editor/table.tsx
  yarn.lock
Labels: enhancement, dependencies, Review effort [1-5]: 2

#140 Cleanup JDM editor files and update version
  package.json
  src/stories/DecisionEditor.stories.tsx
Labels: enhancement, other, Review effort [1-5]: 1

#141 Add icons for chart & update version
  package.json
  src/components/ui/icon/types.ts
  yarn.lock
Labels: enhancement, Review effort [1-5]: 2, other

#142 Update icons & version
  package.json
  src/components/ui/icon/types.ts
Labels: Review effort [1-5]: 2

#143 Update icon & version
  package.json
  src/components/ui/icon/types.ts
Labels: Review effort [1-5]: 1

#144 Extend menu component props
  package.json
  src/components/ui/menu/Menu.tsx
  src/components/ui/menu/types.ts
  src/stories/Menu.stories.tsx
Labels: Review effort [1-5]: 2
