Repository awell-health/design-system, pull requests merged in 2025-01, with the labels that each got.

#169 Form section fix
  package.json
  src/components/ui/form/form-section/FormSection.spec.tsx
  src/components/ui/form/form-section/FormSection.tsx
  style.css
Labels: Review effort [1-5]: 2

#170 Add date range component
  package.json
  src/components/index.ts
  src/components/ui/date-range-select/DateRangeSelect.tsx
  src/components/ui/date-range-select/index.ts
  src/components/ui/icon/types.ts
  src/stories/DateRangeSelect.stories.tsx
  style.css
  yarn.lock
Labels: Review effort [1-5]: 4

#171 Cleanup date range picker & dependencies
  package.json
  src/components/ui/date-range-select/DateRangeSelect.spec.tsx
  src/components/ui/date-range-select/DateRangeSelect.tsx
  src/components/ui/date-range-select/__snapshots__/DateRangeSelect.spec.tsx.snap
  src/components/ui/form/select/__snapshots__/select.spec.tsx.snap
  src/stories/Form/Select.stories.tsx
  yarn.lock
Labels: Review effort [1-5]: 3

#173 Tooltip
  package.json
  src/components/ui/date-range-select/__snapshots__/DateRangeSelect.spec.tsx.snap
  src/components/ui/tooltip/__snapshots__/tooltip.spec.tsx.snap
  src/components/ui/tooltip/tooltip.spec.tsx
  src/components/ui/tooltip/tooltip.tsx
  src/stories/Tooltip.stories.tsx
  style.css
  styles/globals.css
  styles/react-tooltip.css
  yarn.lock
Labels: Review effort [1-5]: 4

#175 Update tooltip props
  package.json
  src/components/ui/tooltip/tooltip.tsx
  src/stories/Tooltip.stories.tsx
  style.css
Labels: Review effort [1-5]: 3

#174 ET-799-update-date-range-to-allow-for-no-initial-dates
  README.md
  src/components/ui/date-range-select/DateRangeSelect.tsx
  src/components/ui/date-range-select/__snapshots__/DateRangeSelect.spec.tsx.snap
  src/stories/DateRangeSelect.stories.tsx
Labels: Review effort [1-5]: 3

#176 Add notification icons
  package.json
  src/components/ui/icon/types.ts
Labels: Review effort [1-5]: 1

#177 Add new size for action icon
  package.json
  src/components/ui/action-icon/action-icon.tsx
  src/components/ui/date-range-select/__snapshots__/DateRangeSelect.spec.tsx.snap
  style.css
Labels: Review effort [1-5]: 2

#179 Remove modal overflow hidden from background
  package.json
  src/components/ui/date-range-select/__snapshots__/DateRangeSelect.spec.tsx.snap
  src/components/ui/modal/Modal.tsx
  src/components/ui/modal/__snapshots__/Modal.spec.tsx.snap
Labels: Review effort [1-5]: 2

#180 Add error state to select
  package.json
  src/components/ui/form/select/select.tsx
  src/stories/Form/Select.stories.tsx
  style.css
Labels: Review effort [1-5]: 2

#181 Update date range styling & specs
  package.json
  src/components/ui/date-range-select/DateRangeSelect.spec.tsx
  src/components/ui/date-range-select/DateRangeSelect.tsx
  src/components/ui/date-range-select/__snapshots__/DateRangeSelect.spec.tsx.snap
  style.css
Labels: Review effort [1-5]: 3

#182 Copy
  package.json
  src/components/index.ts
  src/components/ui/copy-text/__snapshots__/copy-text.spec.tsx.snap
  src/components/ui/copy-text/copy-text.spec.tsx
  src/components/ui/copy-text/copy-text.tsx
  src/components/ui/copy-text/index.ts
  src/components/ui/date-range-select/DateRangeSelect.spec.tsx
  src/components/ui/icon/types.ts
  src/stories/CopyText.stories.tsx
  style.css
Labels: Review effort [1-5]: 3

#183 Extend form section component
  package.json
  src/components/ui/copy-text/__snapshots__/copy-text.spec.tsx.snap
  src/components/ui/date-range-select/DateRangeSelect.spec.tsx
  src/components/ui/date-range-select/__snapshots__/DateRangeSelect.spec.tsx.snap
  src/components/ui/form/form-section/FormSection.spec.tsx
  src/components/ui/form/form-section/FormSection.tsx
  src/components/ui/form/form-section/__snapshots__/FormSection.spec.tsx.snap
  style.css
Labels: Review effort [1-5]: 2
