Repository awell-health/design-system, pull requests merged in 2025-03, with the labels that each got.

#190 Add skeleton loader export & new icons
  package.json
  src/components/index.ts
  src/components/ui/icon/types.ts
Labels: Review effort 2/5

#188 feat(icon): add data point value type icon story
  src/components/ui/data-point-icon/data-point-icon.tsx
  src/components/ui/data-point-icon/index.ts
  src/components/ui/data-point-icon/types.ts
  src/components/ui/icon/types.ts
  src/stories/Icons/DataPointValueType.stories.tsx
  src/stories/Icons/IconGallery.stories.tsx
  style.css
Labels: Review effort 2/5

#191 Export data icon component & update version
  package.json
  src/components/index.ts
  src/components/ui/data-point-icon/__snapshots__/data-point-icon.spec.tsx.snap
  src/components/ui/data-point-icon/data-point-icon.spec.tsx
Labels: Review effort 1/5

#192 Form section updates
  package.json
  src/components/ui/form/checkbox/checkbox.tsx
  src/components/ui/form/form-section/FormSection.tsx
  src/components/ui/form/form-section/__snapshots__/FormSection.spec.tsx.snap
  style.css
Labels: Review effort 2/5

#193 Change data icon types to match data ingestion module
  package.json
  src/components/ui/data-point-icon/data-point-icon.spec.tsx
  src/components/ui/data-point-icon/data-point-icon.tsx
  src/components/ui/data-point-icon/index.ts
  src/components/ui/data-point-icon/types.ts
  src/stories/Icons/DataPointValueType.stories.tsx
Labels: Review effort 3/5

#194 Update icons and alert props
  package.json
  src/components/ui/alert/alert.tsx
  src/components/ui/icon/types.ts
Labels: Review effort 2/5

#195 extend select to support group types
  package.json
  src/components/ui/form/select/index.ts
  src/components/ui/form/select/select.tsx
  src/components/ui/form/select/types.ts
  src/stories/Form/Select.stories.tsx
  style.css
Labels: Review effort 2/5

#196 Alert version patch
  package.json
  src/components/ui/alert/alert.tsx
  style.css
Labels: Review effort 2/5

#200 rev-60-adjust-by-days-should-only-accept-positive-numbers
  src/components/ui/form/input/input.tsx
Labels: Review effort 2/5

#202 Extend select input with custom display for single value
  package.json
  src/components/ui/form/select/select.tsx
  src/components/ui/form/select/types.ts
  src/stories/Form/Select.stories.tsx
Labels: Review effort 3/5

#203 Extend select item type with metadata
  package.json
  src/components/ui/form/select/types.ts
Labels: Review effort 2/5

#206 [VIS-91] Add ListInput component
  package.json
  src/components/index.ts
  src/components/ui/form/list-input/ListInput.spec.tsx
  src/components/ui/form/list-input/ListInput.tsx
  src/components/ui/form/list-input/__snapshots__/ListInput.spec.tsx.snap
  src/components/ui/form/list-input/index.ts
  src/stories/Form/ListInput.stories.tsx
  style.css
Labels: Review effort 3/5

#207 ListInput: useEffect dependency fix
  package.json
  src/components/ui/form/list-input/ListInput.tsx
Labels: Review effort 1/5

#208 feat(copy-text): inline is definitely the way to go!
  package.json
  src/components/ui/copy-text/__snapshots__/copy-text.spec.tsx.snap
  src/components/ui/copy-text/copy-text.tsx
  src/components/ui/data-point-icon/data-point-icon.tsx
  src/stories/CopyText.stories.tsx
  style.css
  styles/globals.css
  tailwind.config.js
Labels: Review effort 4/5

#209 Example form
  package.json
  src/components/ui/button/button.tsx
  src/components/ui/button/index.ts
  src/components/ui/form/form-buttons/FormButtons.spec.tsx
  src/components/ui/form/form-buttons/FormButtons.tsx
  src/components/ui/form/form-buttons/__snapshots__/FormButtons.spec.tsx.snap
  src/components/ui/form/form-buttons/index.ts
  src/components/ui/form/form-content/FormContent.spec.tsx
  src/components/ui/form/form-content/FormContent.tsx
  src/components/ui/form/form-content/__snapshots__/FormContent.spec.tsx.snap
  src/components/ui/form/form-content/index.ts
  src/components/ui/form/input/input.tsx
  src/stories/Form/Form.stories.tsx
  style.css
Labels: Review effort 3/5

#210 Example form
  package.json
  src/components/index.ts
  src/components/ui/form/form-buttons/__snapshots__/form-buttons.spec.tsx.snap
  src/components/ui/form/form-buttons/form-buttons.spec.tsx
  src/components/ui/form/form-buttons/form-buttons.tsx
  src/components/ui/form/form-buttons/index.ts
  src/components/ui/form/form-content/__snapshots__/form-content.spec.tsx.snap
  src/components/ui/form/form-content/form-content.spec.tsx
  src/components/ui/form/form-content/form-content.tsx
  src/components/ui/form/form-content/index.ts
  src/components/ui/form/form-section/FormSection.tsx
  src/components/ui/form/input/__snapshots__/input.spec.tsx.snap
  src/components/ui/form/input/input.tsx
  src/components/ui/form/label/index.ts
  src/components/ui/form/label/label.spec.tsx
  src/components/ui/form/label/label.tsx
  src/components/ui/form/select/__snapshots__/select.spec.tsx.snap
  src/components/ui/form/select/select.tsx
  src/components/ui/form/textarea/__snapshots__/textarea.spec.tsx.snap
  src/components/ui/form/textarea/textarea.tsx
  src/stories/Form/Form.stories.tsx
  src/stories/Form/FormContent.stories.tsx
  style.css
Labels: Review effort 3/5

#212 Fix file upload drag over flickering (re-rendering of the component)
  package.json
  src/components/ui/file-upload/__snapshots__/file-upload.spec.tsx.snap
  src/components/ui/file-upload/file-upload.tsx
  style.css
Labels: Review effort 3/5

#213 Fix file upload overlay styling
  package.json
  src/components/ui/file-upload/__snapshots__/file-upload.spec.tsx.snap
  src/components/ui/file-upload/file-upload.tsx
  style.css
Labels: Review effort 2/5
